namespace L2sniffer.Packets.DataStructs;

public class OtherCharacterInfo : DataStruct
{
    public Coordinates3d Coordinates = null!;
    public uint Heading;
    public uint ObjectId;
    public string Name;
    public uint Race;
    public uint Sex;
    public uint ClassOrBaseClassId;
    public uint Head;
    public uint RHand;
    public uint LHand;
    public uint Gloves;
    public uint Chest;
    public uint Legs;
    public uint Feet;
    public uint Back;
    public uint LRHand;
    public uint Hair;
    public uint PvpFlag;
    public uint Carma;
    public uint MAttackSpeed;
    public uint PAttackSpeed;
    public MovementSpeeds MovementSpeeds;
    public double AttackSpeedMultiplier;
    public double CollisionRadium;
    public double CollisionHeight;
    public uint HairStyle;
    public uint HairColor;
    public uint FaceType;
    public string Title;
    public uint ClanId;
    public uint ClanCrestId;
    public uint AllyId;
    public uint AllyCrestId;
    public byte IsSitting;
    public byte IsRunning;
    public byte IsInCombat;
    public byte IsAlikeDead;
    public byte IsInvisible;
    public byte MountType;
    public byte PrivateStoreType;
    public ushort CubicsSize;
    public ushort[] Cubics;
    public uint AbnormalEffect;
    public ushort RecommendationLevel;
    public byte MountedEnchantEffect;
    public uint ClanCrestLargeId;
    public byte IsFishing;
    public Coordinates3d FishCoordinates;
    public uint NameColor;

    public override void ReadFields(ref FieldsReader reader)
    {
        reader.Read(out Coordinates);
        reader.Read(out Heading);
        reader.Read(out ObjectId);
        reader.Read(out Name);
        reader.Read(out Race);
        reader.Read(out Sex);
        reader.Read(out ClassOrBaseClassId);
        reader.Read(out uint underwear);
        reader.Read(out Head);
        reader.Read(out RHand);
        reader.Read(out LHand);
        reader.Read(out Gloves);
        reader.Read(out Chest);
        reader.Read(out Legs);
        reader.Read(out Feet);
        reader.Read(out Back);
        reader.Read(out LRHand);
        reader.Read(out Hair);
        reader.Read(out PvpFlag);
        reader.Read(out Carma);
        reader.Read(out MAttackSpeed);
        reader.Read(out PAttackSpeed);
        reader.Read(out PvpFlag);
        reader.Read(out Carma);
        reader.Read(out MovementSpeeds);
        reader.Read(out AttackSpeedMultiplier);
        reader.Read(out CollisionRadium);
        reader.Read(out CollisionHeight);
        reader.Read(out HairStyle);
        reader.Read(out HairColor);
        reader.Read(out FaceType);
        reader.Read(out Title);
        reader.Read(out ClanId);
        reader.Read(out ClanCrestId);
        reader.Read(out AllyId);
        reader.Read(out AllyCrestId);
        reader.Read(out uint siegeFlags);
        reader.Read(out IsSitting);
        reader.Read(out IsRunning);
        reader.Read(out IsInCombat);
        reader.Read(out IsAlikeDead);
        reader.Read(out IsInvisible);
        reader.Read(out MountType);
        reader.Read(out PrivateStoreType);
        reader.Read(out CubicsSize);
        Cubics = new ushort[this.CubicsSize];
        reader.Read(ref Cubics);
        reader.Read(out byte findPartyMembers);
        reader.Read(out AbnormalEffect);
        reader.Read(out byte _);
        reader.Read(out RecommendationLevel);
        reader.Read(out uint _);
        reader.Read(out uint _);
        reader.Read(out uint _);
        reader.Read(out MountedEnchantEffect);
        reader.Read(out byte _);
        reader.Read(out ClanCrestLargeId);
        reader.Read(out byte _);
        reader.Read(out byte heroAura);
        reader.Read(out IsFishing);
        reader.Read(out FishCoordinates);
        reader.Read(out NameColor);
    }
}