namespace L2sniffer.Packets.GC;

public enum GameClientPacketTypes : byte
{
    ProtocolVersion = 0x00,
    MoveBackwardToLocation = 0x01,
    Say = 0x02,
    EnterWorld = 0x03,
    Action = 0x04,
    AuthRequest = 0x08,
    Logout = 0x09,
    AttackRequest = 0x0A,
    CharacterCreate = 0x0B,
    CharacterDelete = 0x0C,
    CharacterSelected = 0x0D,
    NewCharacter = 0x0e,
    RequestItemList = 0x0F,
    RequestUnEquipItem = 0x11,
    RequestDropItem = 0x12,
    UseItem = 0x14,
    TradeRequest = 0x15,
    AddTradeItem = 0x16,
    TradeDone = 0x17,
    DummyPacket = 0x1a,
    RequestSocialAction = 0x1B,
    ChangeMoveType = 0x1C,

    // устарел. Теперь юзается 'RequestActionUse'
    ChangeWaitType = 0x1D,

    // устарел. Теперь юзается 'RequestActionUse'
    RequestSellItem = 0x1E,
    RequestBuyItem = 0x1F,
    RequestLinkHtml = 0x20,
    RequestBypassToServer = 0x21,
    RequestBBSWrite = 0x22,
    DummyPacket2 = 0x23,
    RequestJoinPledge = 0x24,
    RequestAnswerJoinPledge = 0x25,
    RequestWithdrawalPledge = 0x26,
    RequestOustPledgeMember = 0x27,
    DismissPledge = 0x28,
    RequestJoinParty = 0x29,
    RequestAnswerJoinParty = 0x2A,
    RequestWithDrawalParty = 0x2B,
    RequestOustPartyMember = 0x2C,
    RequestDismissParty = 0x2d,
    DummyPacket3 = 0x2e,
    RequestMagicSkillUse = 0x2F,
    Appearing = 0x30,
    RequestWarhouseDepositList = 0x31,
    SendWareHouseWithDrawList = 0x32,
    RequestShortCutReg = 0x33,
    DummyPacket4 = 0x34,
    RequestShortCutDel = 0x35,
    CannotMoveAnymore = 0x36,
    RequestTargetCanceld = 0x37,
    Say2 = 0x38,
    RequestPledgeMemberList = 0x3C,
    DummyPacket5 = 0x3e,
    RequestSkillList = 0x3F,
    MoveWithDelta = 0x41,
    RequestGetOnVehicle = 0x42,
    RequestGetOffVehicle = 0x43,
    AnswerTradeRequest = 0x44,
    RequestActionUse = 0x45,
    RequestRestart = 0x46,
    RequestSiegeInfo = 0x47,
    ValidatePosition = 0x48,
    RequestSEKCustom = 0x49,
    StartRotating = 0x4A,
    FinishRotating = 0x4B,
    RequestStartPledgeWar = 0x4D,
    RequestReplyStartPledgeWar = 0x4e,
    RequestStopPledgeWar = 0x4F,
    RequestReplyStopPledgeWar = 0x50,
    RequestSurrenderPledgeWar = 0x51,
    RequestReplySurrenderPledgeWar = 0x52,
    RequestSetPledgeCrest = 0x53,
    RequestGiveNickName = 0x55,
    RequestShowBoard = 0x57,
    RequestEnchantItem = 0x58,
    RequestDestroyItem = 0x59,
    SendBypassBuildCmd = 0x5b,
    RequestMoveToLocationInVehicle = 0x5c,
    CannotMoveAnymoreInVehicle = 0x5d,
    RequestFriendInvite = 0x5E,
    RequestAnswerFriendInvite = 0x5F,
    RequestFriendList = 0x60,
    RequestFriendDel = 0x61,
    CharacterRestore = 0x62,
    RequestQuestList = 0x63,
    RequestQuestAbort = 0x64,
    RequestPledgeInfo = 0x66,
    RequestPledgeExtendedInfo = 0x67,
    RequestPledgeCrest = 0x68,
    RequestSurrenderPersonally = 0x69,
    RequestRide = 0x6A,
    RequestAquireSkillInfo = 0x6B,
    RequestAquireSkill = 0x6C,
    RequestRestartPoint = 0x6D,
    RequestGmCommand = 0x6E,
    RequestPartyMatchConfig = 0x6F,
    RequestPartyMatchList = 0x70,
    RequestPartyMatchDetail = 0x71,
    RequestCrystallizeItem = 0x72,
    RequestPrivateStoreManageSell = 0x73,
    SetPrivateStoreListSell = 0x74,
    RequestPrivateStoreManageCancel = 0x75,
    RequestPrivateStoreQuitSell = 0x76,
    SetPrivateStoreMsgSell = 0x77,
    RequestPrivateStoreList = 0x78,
    RequestPrivateStoreBuy = 0x79,
    ReviveReply = 0x7a,
    RequestTutorialLinkHtml = 0x7b,
    RequestTutorialPassCmdToServer = 0x7c,
    RequestTutorialQuestionMark = 0x7d,
    RequestTutorialClientEvent = 0x7e,
    RequestPetition = 0x7d,
    RequestPetitionCancel = 0x80,
    RequestGmList = 0x81,
    RequestJoinAlly = 0x82,
    RequestAnswerJoinAlly = 0x83,
    AllyLeave = 0x84,
    AllyDismiss = 0x85,
    RequestDismissAlly = 0x86,
    RequestSetAllyCrest = 0x87,
    RequestAllyCrest = 0x88,
    RequestChangePetName = 0x89,
    RequestPetUseItem = 0x8A,
    RequestGiveItemToPet = 0x8B,
    RequestGetItemFromPet = 0x8C,
    RequestAllyInfo = 0x8E,
    RequestPetGetItem = 0x8F,
    RequestPrivateStoreManageBuy = 0x90,
    SetPrivateStoreListBuy = 0x91,
    RequestPrivateStoreBuyManageCancel = 0x92,
    RequestPrivateStoreQuitBuy = 0x93,
    SetPrivateStoreMsgBuy = 0x94,
    RequestPrivateStoreBuyList = 0x95,
    RequestPrivateStoreSell = 0x96,
    SendTimeCheckPacket = 0x97,
    RequestStartAllianceWar = 0x98,
    ReplyStartAllianceWar = 0x99,
    RequestStopAllianceWar = 0x9A,
    ReplyStopAllianceWar = 0x9b,
    RequestSurrenderAllianceWar = 0x9c,
    RequestSkillCoolTime = 0x9d,
    RequestPackageSendableItemList = 0x9e,
    RequestPackageSend = 0x9f,
    RequestBlock = 0xA0,
    RequestCastleSiegeInfo = 0xa1,
    RequestSiegeAttackerList = 0xA2,
    RequestSiegeDefenderList = 0xa3,
    RequestJoinSiege = 0xA4,
    RequestConfirmSiegeWaitingList = 0xa5,
    RequestSetCastleSiegeTime = 0xa6,
    MultiSellChoose = 0xa7,
    NetPing = 0xA8,
    RequestUserCommand = 0xaa,
    SnoopQuit = 0xab,
    RequestRecipeBookOpen = 0xAC,
    RequestRecipeBookDestroy = 0xad,
    RequestRecipeItemMakeInfo = 0xae,
    RequestRecipeItemMakeSelf = 0xaf,
    RequestRecipeShopManageList = 0xb0,
    RequestRecipeShopMessageSet = 0xb1,
    RequestRecipeShopListSet = 0xb2,
    RequestRecipeShopManageQuit = 0xb3,
    RequestRecipeShopMakeInfo = 0xb5,
    RequestRecipeShopMakeItem = 0xb6,
    RequestRecipeShopManagePrev = 0xb7,
    ObserverReturn = 0xb8,
    RequestEvaluate = 0xB9,
    RequestHennaList = 0xBA,
    RequestHennaItemInfo = 0xBB,
    RequestHennaEquip = 0xBC,
    RequestPledgePower = 0xc0,
    RequestMakeMacro = 0xC1,
    RequestDeleteMacro = 0xC2,
    RequestWearItem = 0xc6,
    RequestSSQStatus = 0xc7,
    GameGuardReply = 0xca,
    RequestSendFriendMsg = 0xcc,
    RequestShowMiniMap = 0xcd,
    RequestAutoSoulShot = 0xCF,

//    RequestRecordVideo = 0xCF,??
    RequestExEnchantSkillInfo = 0xD0,

    //:06,
    RequestExEnchantSkill = 0xD0,

    //: 07,
    RequestExManorList = 0xD0,

    //: 08,
    RequestExPledgeCrestLarge = 0xD0,

    //:10,
    RequestExSetPledgeCrestLarge = 0xD0,

    // : 11,
    RequestChangePartyLeader = 0xEE,
}